In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
df = pd.read_csv("rentedwheels_vehicle1.csv")
df

id   ac  acceleration_time auto_manual  file_path fuel_electric  \
0   45   AC                1.2      Manual        NaN          Fuel   
1   77   AC                2.1      Manual        NaN      Electric   
2   30  NaN                1.0        Auto        NaN      Electric   
3   31   AC                0.3      Manual        NaN          Fuel   
4   47  NaN                1.8        Auto        NaN          Fuel   
5   42   AC                2.5      Manual        NaN          Fuel   
6   74  NaN                1.1        Auto        NaN      Electric   
7   61   AC                2.1      Manual        NaN          Fuel   
8   65   AC                2.1        Auto        NaN          Fuel   
9   67   AC                2.1      Manual        NaN          Fuel   
10  75   AC                1.1      Manual        NaN          Fuel   
11  76   AC                2.3      Manual        NaN          Fuel   

    max_power  seats  top_speed  type  \
0       520.0      5        300   NaN   
1       300.0      3        210   NaN   
2         NaN      2        200   NaN   
3       400.0      2        350   NaN   
4       310.0      2        180   NaN   
5       250.0      8        200   NaN   
6       300.0      2        210   NaN   
7       230.0      4        300   NaN   
8       210.0      2        300   NaN   
9       300.0      2        350   NaN   
10      340.0      6        500   NaN   
11      392.0      4        250   NaN   

                                        vehicle_image   vehicle_name  \
0   https://firebasestorage.googleapis.com/v0/b/re...    Land Rover    
1   https://firebasestorage.googleapis.com/v0/b/re...         Tesla    
2   https://firebasestorage.googleapis.com/v0/b/re...         BMW GS   
3   https://firebasestorage.googleapis.com/v0/b/re...        Mustang   
4   https://firebasestorage.googleapis.com/v0/b/re...  Royal Enfield   
5   https://firebasestorage.googleapis.com/v0/b/re...        Scorpio   
6   https://firebasestorage.googleapis.com/v0/b/re...          Yatri   
7   https://firebasestorage.googleapis.com/v0/b/re...    Rolls Royce   
8   https://firebasestorage.googleapis.com/v0/b/re...         Avanti   
9   https://firebasestorage.googleapis.com/v0/b/re...        Ferrari   
10  https://firebasestorage.googleapis.com/v0/b/re...         Pajero   
11  https://firebasestorage.googleapis.com/v0/b/re...    Ford Raptor   

   vehicle_number  vehicle_price  \
0       B AA 9080            400   
1       B AA 7655            200   
2       B AA 4321            200   
3       B AA 9999            400   
4       B AA 0092            100   
5       B AA 6665            200   
6       B AA 2992            100   
7       B AA 2322            200   
8       B AA 2132            200   
9       B AA 5544            200   
10      B AA 8888            200   
11      B AA 9809            200   

                                       vehicle_rating  vehicle_review  \
0                                                   0               0   
1                                                   0               0   
2   {"ERROR_MSG":"Request processing failed; neste...               1   
3                                                   0               0   
4                                                   0               0   
5                                                   0               0   
6                                                   0               0   
7                                                   0               0   
8                                                   0               0   
9                                                   0               0   
10                                                  0               0   
11                                                  0               0   

    vehicle_type vehicle_status  
0         Luxury            NaN  
1       Electric        pending  
2   Two-Wheelers            NaN  
3         Sports            NaN  
4   Two-Wheelers    

In [3]:
features = ['ac', 'acceleration_time', 'auto_manual', 'file_path', 'fuel_electric','max_power','seats','top_speed','type','vehicle_image','vehicle_name','vehicle_number','vehicle_price','vehicle_rating','vehicle_review','vehicle_type','vehicle_status']
for feature in features:
    df[feature] = df[feature].fillna('')

In [11]:
def combined_features(row):
    return str(row['ac']) + " " + str(row['acceleration_time']) + " " +str(row['auto_manual']) + " " + str(row['file_path']) + " " +str(row['fuel_electric']) + " " + str(row['max_power']) + " " + str(row['seats']) + " " + str(row['top_speed']) + " " + str(row['type']) + " " + str(row['vehicle_image']) + " " + str(row['vehicle_number']) + " " + str(row['vehicle_price']) +" " + str(row['vehicle_rating']) + " " + str(row['vehicle_review']) + " " + str(row['vehicle_type']) + " " + str(row['vehicle_status']) + " " + str(row['file_path'])
df["combined_features"] = df.apply(combined_features, axis =1)

In [12]:
cv = CountVectorizer()

In [13]:
count_matrix = cv.fit_transform(df["combined_features"])

In [14]:
count_array = count_matrix.toarray()

In [15]:
cosine_sim = cosine_similarity(count_matrix)

In [16]:
vis = pd.DataFrame(data = cosine_sim)

In [17]:
vis

0         1         2         3         4         5         6   \
0   1.000000  0.585239  0.428384  0.687836  0.548387  0.656571  0.548387   
1   0.585239  1.000000  0.536875  0.537373  0.523635  0.597081  0.646843   
2   0.428384  0.536875  1.000000  0.415199  0.535480  0.518999  0.562254   
3   0.687836  0.537373  0.415199  1.000000  0.531510  0.606061  0.500244   
4   0.548387  0.523635  0.535480  0.531510  1.000000  0.531510  0.677419   
5   0.656571  0.597081  0.518999  0.606061  0.531510  1.000000  0.500244   
6   0.548387  0.646843  0.562254  0.500244  0.677419  0.500244  1.000000   
7   0.709677  0.616041  0.481932  0.625305  0.548387  0.719101  0.548387   
8   0.603251  0.636656  0.527046  0.584685  0.603251  0.615457  0.635001   
9   0.645161  0.646843  0.508706  0.656571  0.580645  0.656571  0.580645   
10  0.635001  0.636656  0.500694  0.584685  0.571501  0.677003  0.539751   
11  0.594040  0.626936  0.493049  0.575758  0.562775  0.666667  0.531510   

          7         8         9         10        11  
0   0.709677  0.603251  0.645161  0.635001  0.594040  
1   0.616041  0.636656  0.646843  0.636656  0.626936  
2   0.481932  0.527046  0.508706  0.500694  0.493049  
3   0.625305  0.584685  0.656571  0.584685  0.575758  
4   0.548387  0.603251  0.580645  0.571501  0.562775  
5   0.719101  0.615457  0.656571  0.677003  0.666667  
6   0.548387  0.635001  0.580645  0.539751  0.531510  
7   1.000000  0.635001  0.677419  0.666751  0.625305  
8   0.635001  1.000000  0.698501  0.625000  0.615457  
9   0.677419  0.698501  1.000000  0.666751  0.656571  
10  0.666751  0.625000  0.666751  1.000000  0.677003  
11  0.625305  0.615457  0.656571  0.677003  1.000000

In [20]:
def get_name_from_id(id):
    return df[df.id == id]["vehicle_name"].values[0]

vehicle_index = get_name_from_id(45)
vehicle_index

'Land Rover '

In [37]:
similar_vehicles = list(enumerate(cosine_sim))
sorted_similar_vehicles = sorted(similar_vehicles, key=lambda x: x[1][1], reverse=True)
sorted_similar_vehicles

[(1,
  array([0.58523905, 1.        , 0.53687549, 0.53737329, 0.52363494,
         0.59708143, 0.64684316, 0.6160411 , 0.63665602, 0.64684316,
         0.63665602, 0.62693551])),
 (6,
  array([0.5483871 , 0.64684316, 0.56225353, 0.50024432, 0.67741935,
         0.50024432, 1.        , 0.5483871 , 0.63500064, 0.58064516,
         0.53975054, 0.53150959])),
 (9,
  array([0.64516129, 0.64684316, 0.50870557, 0.65657067, 0.58064516,
         0.65657067, 0.58064516, 0.67741935, 0.6985007 , 1.        ,
         0.66675067, 0.65657067])),
 (8,
  array([0.6032506 , 0.63665602, 0.52704628, 0.58468458, 0.6032506 ,
         0.61545745, 0.63500064, 0.63500064, 1.        , 0.6985007 ,
         0.625     , 0.61545745])),
 (10,
  array([0.63500064, 0.63665602, 0.50069396, 0.58468458, 0.57150057,
         0.6770032 , 0.53975054, 0.66675067, 0.625     , 0.66675067,
         1.        , 0.6770032 ])),
 (11,
  array([0.59404013, 0.62693551, 0.49304933, 0.57575758, 0.56277486,
         0.66666667, 0.531509